export const TAURI_COMMANDS = {
  authorizeImageAsset: 'authorize_image_asset',
  consumeStartupOpenRequest: 'consume_startup_open_request',
  consumeWindowOpenRequest: 'consume_window_open_request',
  createWorkspaceEntry: 'create_workspace_entry',
  fetchRemoteImage: 'fetch_remote_image',
  importDocumentImage: 'import_document_image',
  listWorkspaceEntries: 'list_workspace_entries',
  notifyFrontendReady: 'notify_frontend_ready',
  openDocument: 'open_document',
  openEditorWindow: 'open_editor_window',
  printDocument: 'print_document',
  refreshNativeMenuShortcuts: 'refresh_native_menu_shortcuts',
  renameWorkspaceEntry: 'rename_workspace_entry',
  resolveDocumentImagePath: 'resolve_document_image_path',
  revealInFinder: 'reveal_in_finder',
  revealStartupOpenLog: 'reveal_startup_open_log',
  saveDocument: 'save_document',
  setWindowBackgroundColor: 'set_window_background_color',
  trashWorkspaceEntry: 'trash_workspace_entry',
  unwatchWorkspace: 'unwatch_workspace',
  watchWorkspace: 'watch_workspace',
} as const;

export type TauriCommandName = (typeof TAURI_COMMANDS)[keyof typeof TAURI_COMMANDS];
