import { Schema, type Node as PMNode } from '@tiptap/pm/model';

export function createMarkdownCompatSchema(): Schema {
  return new Schema({
    nodes: {
      doc: { content: 'block+' },
      paragraph: {
        group: 'block',
        content: 'inline*',
        parseDOM: [{ tag: 'p' }],
        toDOM: () => ['p', 0],
      },
      heading: {
        group: 'block',
        content: 'headingMarker? inline*',
        attrs: { level: { default: 1 } },
        defining: true,
        parseDOM: [1, 2, 3, 4, 5, 6].map((level) => ({ tag: `h${level}`, attrs: { level } })),
        toDOM: (node: PMNode) => [`h${node.attrs.level}`, 0],
      },
      headingMarker: {
        inline: true,
        atom: true,
        selectable: true,
        attrs: { level: { default: 1 } },
        parseDOM: [{ tag: 'span[data-heading-marker]' }],
        toDOM: (node: PMNode) => [
          'span',
          { 'data-heading-marker': '', 'data-level': node.attrs.level },
          '#'.repeat(node.attrs.level) + ' ',
        ],
      },
      blockquote: {
        group: 'block',
        content: 'block+',
        parseDOM: [{ tag: 'blockquote' }],
        toDOM: () => ['blockquote', 0],
      },
      bulletList: {
        group: 'block',
        content: '(listItem | taskItem)+',
        parseDOM: [{ tag: 'ul' }],
        toDOM: () => ['ul', 0],
      },
      orderedList: {
        group: 'block',
        content: 'listItem+',
        attrs: { start: { default: 1 } },
        parseDOM: [{ tag: 'ol' }],
        toDOM: () => ['ol', 0],
      },
      taskList: {
        group: 'block',
        content: 'taskItem+',
        parseDOM: [{ tag: 'ul[data-type="task-list"]' }],
        toDOM: () => ['ul', { 'data-type': 'task-list' }, 0],
      },
      listItem: {
        content: 'paragraph block*',
        parseDOM: [{ tag: 'li' }],
        toDOM: () => ['li', 0],
      },
      taskItem: {
        attrs: { checked: { default: false } },
        defining: true,
        content: 'paragraph block*',
        parseDOM: [{ tag: 'li[data-type="task-item"]' }],
        toDOM: () => ['li', { 'data-type': 'task-item' }, 0],
      },
      codeBlock: {
        group: 'block',
        content: 'text*',
        marks: '',
        code: true,
        attrs: { language: { default: null }, languageLabel: { default: null } },
        parseDOM: [{ tag: 'pre' }],
        toDOM: () => ['pre', ['code', 0]],
      },
      hardBreak: {
        inline: true,
        group: 'inline',
        selectable: false,
        parseDOM: [{ tag: 'br' }],
        toDOM: () => ['br'],
      },
      horizontalRule: {
        group: 'block',
        parseDOM: [{ tag: 'hr' }],
        toDOM: () => ['hr'],
      },
      image: {
        inline: true,
        group: 'inline',
        attrs: {
          src: { default: '' },
          alt: { default: '' },
          title: { default: null },
        },
        parseDOM: [{ tag: 'img' }],
        toDOM: () => ['img'],
      },
      mathInline: {
        inline: true,
        group: 'inline',
        atom: true,
        attrs: { latex: { default: '' } },
        parseDOM: [{ tag: 'span[data-type="math-inline"]' }],
        toDOM: () => ['span', { 'data-type': 'math-inline' }, 0],
      },
      mathBlock: {
        group: 'block',
        content: 'text*',
        marks: '',
        code: true,
        parseDOM: [{ tag: 'div[data-type="math-block"]' }],
        toDOM: () => ['div', { 'data-type': 'math-block' }, 0],
      },
      mermaidBlock: {
        group: 'block',
        content: 'text*',
        marks: '',
        code: true,
        parseDOM: [{ tag: 'div[data-type="mermaid-block"]' }],
        toDOM: () => ['div', { 'data-type': 'mermaid-block' }, 0],
      },
      callout: {
        group: 'block',
        content: 'block+',
        attrs: {
          type: { default: 'note' },
          title: { default: '' },
        },
        parseDOM: [{ tag: 'div[data-type="callout"]' }],
        toDOM: () => ['div', { 'data-type': 'callout' }, 0],
      },
      frontmatter: {
        group: 'block',
        content: 'text*',
        marks: '',
        code: true,
        parseDOM: [{ tag: 'div[data-type="frontmatter"]' }],
        toDOM: () => ['div', { 'data-type': 'frontmatter' }, 0],
      },
      table: {
        group: 'block',
        content: 'tableRow+',
        tableRole: 'table',
        parseDOM: [{ tag: 'table' }],
        toDOM: () => ['table', ['tbody', 0]],
      },
      tableRow: {
        content: '(tableHeader | tableCell)+',
        tableRole: 'row',
        parseDOM: [{ tag: 'tr' }],
        toDOM: () => ['tr', 0],
      },
      tableHeader: {
        content: 'block+',
        tableRole: 'header_cell',
        isolating: true,
        parseDOM: [{ tag: 'th' }],
        toDOM: () => ['th', 0],
      },
      tableCell: {
        content: 'block+',
        tableRole: 'cell',
        isolating: true,
        parseDOM: [{ tag: 'td' }],
        toDOM: () => ['td', 0],
      },
      wikilink: {
        inline: true,
        group: 'inline',
        atom: true,
        attrs: {
          target: { default: '' },
          alias: { default: '' },
        },
        parseDOM: [{ tag: 'span[data-wikilink]' }],
        toDOM: () => ['span', { 'data-wikilink': '' }, 0],
      },
      text: { group: 'inline' },
      boldOpen: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '**'] },
      boldClose: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '**'] },
      italicOpen: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '*'] },
      italicClose: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '*'] },
      strikeOpen: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '~~'] },
      strikeClose: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '~~'] },
      highlightOpen: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '=='] },
      highlightClose: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '=='] },
      supOpen: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '^'] },
      supClose: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '^'] },
      subOpen: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '~'] },
      subClose: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '~'] },
      codeOpen: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '`'] },
      codeClose: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '`'] },
      linkBracketOpen: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, '['] },
      linkBracketClose: { inline: true, group: 'inline', atom: true, selectable: false, toDOM: () => ['span', {}, ']'] },
      linkUrl: {
        inline: true,
        group: 'inline',
        atom: true,
        selectable: true,
        attrs: { href: { default: '' }, title: { default: null } },
        toDOM: () => ['span', {}, '(url)'],
      },
    },
    marks: {
      bold: { parseDOM: [{ tag: 'strong' }], toDOM: () => ['strong', 0] },
      italic: { parseDOM: [{ tag: 'em' }], toDOM: () => ['em', 0] },
      strike: { parseDOM: [{ tag: 's' }], toDOM: () => ['s', 0] },
      code: { parseDOM: [{ tag: 'code' }], toDOM: () => ['code', 0] },
      highlight: { parseDOM: [{ tag: 'mark' }], toDOM: () => ['mark', 0] },
      link: {
        attrs: {
          href: { default: '' },
          target: { default: null },
          title: { default: null },
        },
        parseDOM: [{ tag: 'a' }],
        toDOM: () => ['a', 0],
      },
      superscript: { parseDOM: [{ tag: 'sup' }], toDOM: () => ['sup', 0] },
      subscript: { parseDOM: [{ tag: 'sub' }], toDOM: () => ['sub', 0] },
    },
  });
}
